using Archy.Features.Placement.ClusterRevisions;
using Archy.Features.Workspaces.AcquireWorkspaceLock;
using Archy.Features.Workspaces.InitializeWorkspace;
using Archy.SharedKernel.Primitives;
using Microsoft.Data.Sqlite;

namespace Archy.Features.Placement.ReadClusterMemberPages;

public sealed class ClusterMemberPageReader(IWorkspaceLockManager lockManager) : IClusterMemberPageReader
{
    public async ValueTask<Result<ClusterMemberPage>> ReadAsync(WorkspaceStateLocation location,string revisionId,string clusterId,int offset,int limit,CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(location);if(string.IsNullOrWhiteSpace(revisionId)||string.IsNullOrWhiteSpace(clusterId)||offset is<0 or>1_000_000||limit is<1 or>200)return ResultFactory.Failure<ClusterMemberPage>(Problem.Validation("Cluster member pages require revision and cluster IDs, offset between 0 and 1000000, and limit between 1 and 200."));
        var lease=await lockManager.AcquireAsync(location,WorkspaceLockMode.Read,TimeSpan.FromSeconds(30),cancellationToken);if(!lease.IsSuccess)return ResultFactory.Failure<ClusterMemberPage>(lease.Problem!);using var held=lease.Value;
        try {SQLitePCL.Batteries_V2.Init();await using var c=new SqliteConnection($"Data Source={location.DatabasePath}");await c.OpenAsync(cancellationToken);var metadata=await MetadataAsync(c,location.WorkspaceId,revisionId,clusterId,cancellationToken);if(metadata is null)return ResultFactory.Failure<ClusterMemberPage>(Problem.NotFound($"Cluster '{clusterId}' was not found in revision '{revisionId}'."));var total=await CountAsync(c,revisionId,clusterId,cancellationToken);await using var q=c.CreateCommand();q.CommandText="SELECT target_kind,target_stable_id,membership_weight FROM cluster_memberships WHERE cluster_revision_id=$revisionId AND cluster_id=$clusterId ORDER BY member_ordinal LIMIT $limit OFFSET $offset;";q.Parameters.AddWithValue("$revisionId",revisionId);q.Parameters.AddWithValue("$clusterId",clusterId);q.Parameters.AddWithValue("$limit",limit);q.Parameters.AddWithValue("$offset",offset);await using var r=await q.ExecuteReaderAsync(cancellationToken);var items=new List<ClusterMember>();while(await r.ReadAsync(cancellationToken))items.Add(new ClusterMember(new ArchitectureTarget(ArchitectureTargetCodec.FromStorageValue(r.GetString(0)),r.GetString(1)),r.GetDouble(2)));return ResultFactory.Success(new ClusterMemberPage(revisionId,clusterId,metadata.Value.Key,metadata.Value.GraphRevision,metadata.Value.Algorithm,metadata.Value.AlgorithmVersion,offset,limit,total,[..items]));}catch(SqliteException e){return ResultFactory.Failure<ClusterMemberPage>(Problem.Storage($"Archy could not read cluster members: {e.Message}"));}
    }
    private static async Task<(string Key,long GraphRevision,string Algorithm,string AlgorithmVersion)?> MetadataAsync(SqliteConnection c,string workspace,string revision,string cluster,CancellationToken ct){await using var q=c.CreateCommand();q.CommandText="SELECT c.cluster_key,cr.graph_revision,cr.algorithm,cr.algorithm_version FROM cluster_memberships cm INNER JOIN cluster_revisions cr ON cr.cluster_revision_id=cm.cluster_revision_id INNER JOIN clusters c ON c.cluster_id=cm.cluster_id WHERE cr.workspace_id=$workspace AND cm.cluster_revision_id=$revision AND cm.cluster_id=$cluster LIMIT 1;";q.Parameters.AddWithValue("$workspace",workspace);q.Parameters.AddWithValue("$revision",revision);q.Parameters.AddWithValue("$cluster",cluster);await using var r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetString(0),r.GetInt64(1),r.GetString(2),r.GetString(3)):null;}
    private static async Task<int> CountAsync(SqliteConnection c,string revision,string cluster,CancellationToken ct){await using var q=c.CreateCommand();q.CommandText="SELECT COUNT(*) FROM cluster_memberships WHERE cluster_revision_id=$revision AND cluster_id=$cluster;";q.Parameters.AddWithValue("$revision",revision);q.Parameters.AddWithValue("$cluster",cluster);return Convert.ToInt32(await q.ExecuteScalarAsync(ct),System.Globalization.CultureInfo.InvariantCulture);}
}
