using Archy.Features.CommandLine;
using Archy.Features.Configuration.LoadEffectiveConfiguration;
using Archy.Features.Workspaces.AcquireWorkspaceLock;
using Archy.Features.Storage.WorkspaceDatabase.Initialize;
using Archy.Features.Storage.WorkspaceDatabase.Check;
using Archy.Features.Storage.WorkspaceDatabase.Backup;
using Archy.Features.Storage.WorkspaceDatabase.Restore;
using Archy.Features.Storage.WorkspaceDatabase.Vacuum;
using Archy.Features.Storage.WorkspaceDatabase.ExportDiagnostics;
using Archy.Features.Analysis.AnalysisRuns;
using Archy.Features.Graph.CommitGraphRevision;
using Archy.Features.Graph.TraverseDependencies;
using Archy.Features.Analysis.InventorySources;
using Archy.Features.Analysis.ExtractCSharpSyntaxFacts;
using Archy.Features.Graph.ReadActiveGraphRevision;
using Archy.Features.Graph.ReadGraphRevision;
using Archy.Features.Graph.ReadGraphPage;
using Archy.Features.Graph.ExploreGraph;
using Archy.Features.Graph.RenderGraphMap;
using Archy.Features.Analysis.AnalyzeWorkspace;
using Archy.Features.Analysis.PlanIncrementalAnalysis;
using Archy.Features.Analysis.WatchWorkspaceChanges;
using Archy.Features.Analysis.MineGitCoChanges;
using Archy.Features.Analysis.ResolveDotNetDependencyRegistrations;
using Archy.Features.Analysis.ResolveDotNetDependencyConsumptions;
using Archy.Features.Analysis.ResolveDotNetConfigurationReads;
using Archy.Features.Analysis.ResolveJsonConfigurationDefinitions;
using Archy.Features.Analysis.ResolveRabbitMqTopology;
using Archy.Features.Analysis.ResolveDotNetMessageContracts;
using Archy.Features.Analysis.ExternalLanguageServerProtocol.EstablishStdioSession;
using Archy.Features.Analysis.LanguageServerProfiles;
using Archy.Features.Analysis.AnalyzeLanguageServerSemantics;
using Archy.Features.Architecture.LayerMembership;
using Archy.Features.Architecture.EnforceLayerDependencies;
using Archy.Features.Architecture.DetectDependencyCycles;
using Archy.Features.Architecture.VerificationBaselines;
using Archy.Features.Architecture.ArchitectureExceptions;
using Archy.Features.Architecture.VerifyArchitecture;
using Archy.Features.Advisories.ComposeUnifiedAdvisories;
using Archy.Features.Memory.Summaries;
using Archy.Features.Memory.ReadSummaryPages;
using Archy.Features.Memory.SummaryBatches;
using Archy.Features.Memory.ComparePublicSurface;
using Archy.Features.Memory.DetermineImportantNodes;
using Archy.Features.Memory.AccumulateTouchedNodes;
using Archy.Features.Memory.ConstructSummaryPrompts;
using Archy.Features.Memory.ValidateSummaryResponses;
using Archy.Features.Memory.PlanSummaryStaleness;
using Archy.Features.Memory.QueueStaleSummaryRegeneration;
using Archy.Features.Memory.BuildDirectorySummaryRollups;
using Archy.Features.Memory.ComposeSessionChangelog;
using Archy.Features.Memory.AuthorizeAiSourceSharing;
using Archy.Features.Memory.GovernModelRequests;
using Archy.Features.Memory.ModelProviders.OpenAi;
using Archy.Features.Memory.ManageModelFailureWork;
using Archy.Features.Duplicates.CompareInterfaceSignatures;
using Archy.Features.Duplicates.SelectEmbeddingChunks;
using Archy.Features.Sidecars.Protocol;
using Archy.Features.Duplicates.ParseJscpdCloneReport;
using Archy.Features.Duplicates.MapStructuralClonesToSymbols;
using Archy.Features.Duplicates.EmbeddingCache;
using Archy.Features.Duplicates.IndexEmbeddings;
using Archy.Features.Duplicates.PartitionEmbeddingCandidates;
using Archy.Features.Duplicates.ScoreRelativeEmbeddingSimilarity;
using Archy.Features.Duplicates.AggregateDuplicateSignals;
using Archy.Features.Duplicates.CheckDataShapeNaming;
using Archy.Features.Duplicates.ApplyDuplicateDecisionFeedback;
using Archy.Features.Duplicates.ComposeDuplicateInspection;
using Archy.Features.Duplicates.EvaluateDuplicateDetection;
using Archy.Features.Duplicates.RetrieveEmbeddingCandidates;
using Archy.Features.Duplicates.ReconcileDuplicateFindingLifecycle;
using Archy.Features.Placement.ComputeModuleCohesion;
using Archy.Features.Placement.ScorePlacementOverlap;
using Archy.Features.Placement.MineSiblingNaming;
using Archy.Features.Placement.AdviseSplitOrAppend;
using Archy.Features.Placement.ApplyPlacementDecisionFeedback;
using Archy.Features.Decisions.ArchitectureDecisions;
using Archy.Features.Decisions.ReadDecisionPages;
using Archy.Features.Sessions.ArchitectureSessions;
using Archy.Features.Sessions.ReplayEventPages;
using Archy.Features.Duplicates.DuplicateFindings;
using Archy.Features.Duplicates.ReadDuplicateObservationPages;
using Archy.Features.Placement.ClusterRevisions;
using Archy.Features.Similarity.BuildSimilarityClusters;
using Archy.Features.Placement.ReadClusterMemberPages;
using Archy.Features.Health.HealthSnapshots;
using Archy.Features.Health.ReadHealthComponentPages;
using Archy.Features.Health.CalculateDocumentationDebt;
using Archy.Features.Health.CalculateArchitectureHealth;
using Archy.Features.Workspaces.LocateWorkspace;
using Archy.Features.Workspaces.ReadRepositoryCommit;
using Archy.Features.Workspaces.InitializeWorkspace;
using Archy.Features.Integrations.GitHooks;
using Archy.Features.Integrations.Codex.PostToolChangedPaths;
using Archy.Features.Integrations.Codex.RecordHookEvents;
using Archy.Features.Integrations.Codex.GenerateManagedAgentsSection;
using Archy.Features.Integrations.Codex.PublishAgentsSnapshot;
using Mediator;
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection();
services.AddSingleton<IWorkspaceLocator, WorkspaceLocator>();
services.AddSingleton<IGitHookDirectoryResolver, GitHookDirectoryResolver>();
services.AddSingleton<IGitHookLifecycle, GitHookLifecycle>();
services.AddSingleton<IRepositoryCommitReader, GitRepositoryCommitReader>();
services.AddSingleton<IRepositoryProvenanceReader, GitRepositoryCommitReader>();
services.AddSingleton<IWorkspaceStateLayout, WorkspaceStateLayout>();
services.AddSingleton<TimeProvider>(TimeProvider.System);
services.AddSingleton<IWorkspaceManifestRepository, WorkspaceManifestRepository>();
services.AddSingleton<IWorkspaceLockManager, WorkspaceLockManager>();
services.AddSingleton<IWorkspaceDatabaseMigrationCatalog>(_ => new WorkspaceDatabaseMigrationCatalog());
services.AddSingleton<IWorkspaceDatabaseInitializer, WorkspaceDatabaseInitializer>();
services.AddSingleton<WorkspaceDatabaseChecker>();
services.AddSingleton<WorkspaceDatabaseBackupCreator>();
services.AddSingleton<WorkspaceDatabaseRestorer>();
services.AddSingleton<WorkspaceDatabaseVacuumService>();
services.AddSingleton<WorkspaceDatabaseDiagnosticsExporter>();
services.AddSingleton<IAnalysisRunRepository, AnalysisRunRepository>();
services.AddSingleton<IGraphRevisionCommitter, GraphRevisionCommitter>();
services.AddSingleton<IGraphTraversalReader, GraphTraversalReader>();
services.AddSingleton<IActiveGraphRevisionReader, ActiveGraphRevisionReader>();
services.AddSingleton<IGraphRevisionSnapshotReader, GraphRevisionSnapshotReader>();
services.AddSingleton<IGraphRevisionPageReader, GraphRevisionPageReader>();
services.AddSingleton<IGraphExplorerReader, GraphExplorerReader>();
services.AddSingleton<IGraphMapReader, GraphMapReader>();
services.AddSingleton<IIncrementalAnalysisPlanner, IncrementalAnalysisPlanner>();
services.AddSingleton<ICSharpSyntaxFactReconciler, CSharpSyntaxFactReconciler>();
services.AddSingleton<IWorkspaceFileWatcher, WorkspaceFileWatcher>();
services.AddSingleton<IGitCoChangeMiner, GitCoChangeMiner>();
services.AddSingleton<IBoundedWorkspacePathSnapshotter, BoundedWorkspacePathSnapshotter>();
services.AddSingleton<IPostToolChangedPathResolver, PostToolChangedPathResolver>();
services.AddSingleton<IRepositorySourceInventory, RepositorySourceInventory>();
services.AddSingleton<ICSharpSyntaxFactExtractor, CSharpSyntaxFactExtractor>();
services.AddSingleton<IExecutablePathProbe, PathExecutablePathProbe>();
services.AddSingleton<ILanguageServerProfileSelector, LanguageServerProfileSelector>();
services.AddSingleton<ILanguageServerSessionFactory, LanguageServerStdioSessionFactory>();
services.AddSingleton<IConfiguredLspSemanticAnalyzer, ConfiguredLspSemanticAnalyzer>();
services.AddSingleton<IWorkspaceAnalyzer, AnalyzeWorkspaceHandler>();
services.AddSingleton<ILayerMembershipResolver, LayerMembershipResolver>();
services.AddSingleton<IHardArchitectureEdgePolicy, HardArchitectureEdgePolicy>();
services.AddSingleton<IArchitectureCycleDetector, ArchitectureCycleDetector>();
services.AddSingleton<ILayerDependencyRuleEvaluator, LayerDependencyRuleEvaluator>();
services.AddSingleton<IArchitectureFindingFactory, ArchitectureFindingFactory>();
services.AddSingleton<IArchitectureBaselinePolicyRepository, ArchitectureBaselinePolicyRepository>();
services.AddSingleton<IArchitectureBaselineComparer, ArchitectureBaselineComparer>();
services.AddSingleton<IArchitectureExceptionPolicyRepository, ArchitectureExceptionPolicyRepository>();
services.AddSingleton<IArchitectureExceptionApplicator, ArchitectureExceptionApplicator>();
services.AddSingleton<IArchitectureVerificationService, ArchitectureVerificationService>();
services.AddSingleton<IUnifiedAdvisoryComposer, UnifiedAdvisoryComposer>();
services.AddSingleton<IDotNetDependencyRegistrationProvider, DotNetDependencyRegistrationProvider>();
services.AddSingleton<IDotNetDependencyConsumptionProvider, DotNetDependencyConsumptionProvider>();
services.AddSingleton<IDotNetConfigurationReadProvider, DotNetConfigurationReadProvider>();
services.AddSingleton<IJsonConfigurationDefinitionProvider, JsonConfigurationDefinitionProvider>();
services.AddSingleton<IRabbitMqTopologyProvider, RabbitMqTopologyProvider>();
services.AddSingleton<IDotNetMessageContractProvider, DotNetMessageContractProvider>();
services.AddSingleton<ISummaryRepository, SummaryRepository>();
services.AddSingleton<ISummaryVersionPageReader, SummaryVersionPageReader>();
services.AddSingleton<ISummaryBatchRepository, SummaryBatchRepository>();
services.AddSingleton<IPublicSurfaceDiffEngine, PublicSurfaceDiffEngine>();
services.AddSingleton<IImportantNodeEligibilityPolicy, ImportantNodeEligibilityPolicy>();
services.AddSingleton<ITouchedNodeSessionAccumulator, TouchedNodeSessionAccumulator>();
services.AddSingleton<ISummaryPromptRedactor, SummaryPromptRedactor>();
services.AddSingleton<ISummaryPromptBuilder, SummaryPromptBuilder>();
services.AddSingleton<IStructuredSummaryResponseValidator, StructuredSummaryResponseValidator>();
services.AddSingleton<ISummaryStalenessPlanner, SummaryStalenessPlanner>();
services.AddSingleton<IStaleSummaryRegenerationWorklist, StaleSummaryRegenerationWorklist>();
services.AddSingleton<IDirectorySummaryRollupBuilder, DirectorySummaryRollupBuilder>();
services.AddSingleton<ISessionChangelogComposer, SessionChangelogComposer>();
services.AddSingleton<IRepositoryAiConsentPolicy, RepositoryAiConsentPolicy>();
services.AddSingleton<IModelRequestGovernor, ModelRequestGovernor>();
services.AddSingleton<IOpenAiApiKeyProvider, EnvironmentOpenAiApiKeyProvider>();
services.AddSingleton(OpenAiProviderOptions.Default);
services.AddSingleton(new HttpClient());
services.AddSingleton<OpenAiResponsesModelProvider>();
services.AddSingleton<IModelFailureWorkRepository, ModelFailureWorkRepository>();
services.AddSingleton<IInterfaceSignatureSimilarityScorer, InterfaceSignatureSimilarityScorer>();
services.AddSingleton<IEmbeddingChunkSelector, CSharpEmbeddingChunkSelector>();
services.AddSingleton<ISidecarProtocolValidator, SidecarProtocolValidator>();
services.AddSingleton<ISidecarMessageCodec, SidecarMessageCodec>();
services.AddSingleton<IJscpdCloneReportParser, JscpdCloneReportParser>();
services.AddSingleton<IStructuralCloneSymbolMapper, StructuralCloneSymbolMapper>();
services.AddSingleton<IEmbeddingCacheRepository, EmbeddingCacheRepository>();
services.AddSingleton<IEmbeddingCacheResolver, EmbeddingCacheResolver>();
services.AddSingleton<IEmbeddingIndexSourceReader, EmbeddingIndexSourceReader>();
services.AddSingleton<EmbeddingIndexer>();
services.AddSingleton<IEmbeddingModelProviderResolver, EmbeddingModelProviderResolver>();
services.AddSingleton<IEmbeddingCandidatePartitioner, EmbeddingCandidatePartitioner>();
services.AddSingleton<IRelativeEmbeddingSimilarityScorer, RelativeEmbeddingSimilarityScorer>();
services.AddSingleton(DuplicateSignalThresholds.Default);
services.AddSingleton<IDuplicateSignalAggregator, DuplicateSignalAggregator>();
services.AddSingleton<IDataShapeNamingChecker, DataShapeNamingChecker>();
services.AddSingleton<IDuplicateDecisionFeedbackPolicy, DuplicateDecisionFeedbackPolicy>();
services.AddSingleton<IDuplicateInspectionComposer, DuplicateInspectionComposer>();
services.AddSingleton<IDuplicateEvaluationReporter, DuplicateEvaluationReporter>();
services.AddSingleton(EmbeddingRetrievalOptions.Default);
services.AddSingleton<IBoundedEmbeddingCandidateRetriever, BoundedEmbeddingCandidateRetriever>();
services.AddSingleton<IDuplicateFindingLifecycleRepository, DuplicateFindingLifecycleRepository>();
services.AddSingleton<IModuleCohesionCalculator, ModuleCohesionCalculator>();
services.AddSingleton<IPlacementOverlapScorer, PlacementOverlapScorer>();
services.AddSingleton<ISiblingNamingConventionMiner, SiblingNamingConventionMiner>();
services.AddSingleton(SplitAppendThresholds.Default);
services.AddSingleton<ISplitAppendAdvisor, SplitAppendAdvisor>();
services.AddSingleton<IPlacementDecisionFeedbackPolicy, PlacementDecisionFeedbackPolicy>();
services.AddSingleton<ArchitectureSessionRepository>();
services.AddSingleton<IArchitectureSessionRepository>(static provider => provider.GetRequiredService<ArchitectureSessionRepository>());
services.AddSingleton<IArchitectureSessionEventReplayReader>(static provider => provider.GetRequiredService<ArchitectureSessionRepository>());
services.AddSingleton<IArchitectureDecisionRepository, ArchitectureDecisionRepository>();
services.AddSingleton<IArchitectureDecisionPageReader, ArchitectureDecisionPageReader>();
services.AddSingleton<IHookEventPublisher, HookEventPublisher>();
services.AddSingleton<ICodexHookEventRecorder, CodexHookEventRecorder>();
services.AddSingleton<IManagedAgentsSectionGenerator, ManagedAgentsSectionGenerator>();
services.AddSingleton<IPostRevisionAgentsPublisher, PostRevisionAgentsPublisher>();
services.AddSingleton<IDuplicateFindingRepository, DuplicateFindingRepository>();
services.AddSingleton<IDuplicateObservationPageReader, DuplicateObservationPageReader>();
services.AddSingleton<IClusterRevisionRepository, ClusterRevisionRepository>();
services.AddSingleton<ISimilarityClusterRepository, SimilarityClusterRepository>();
services.AddSingleton<IClusterMemberPageReader, ClusterMemberPageReader>();
services.AddSingleton<IHealthSnapshotRepository, HealthSnapshotRepository>();
services.AddSingleton<IHealthComponentPageReader, HealthComponentPageReader>();
services.AddSingleton(DocumentationDebtOptions.Default);
services.AddSingleton<IDocumentationDebtCalculator, DocumentationDebtCalculator>();
services.AddSingleton(ArchitectureHealthWeights.Default);
services.AddSingleton<IArchitectureHealthCalculator, ArchitectureHealthCalculator>();
services.AddSingleton<IUserConfigurationPathProvider, UserConfigurationPathProvider>();
services.AddSingleton<ITomlConfigurationParser, TomlConfigurationParser>();
services.AddSingleton<IArchyConfigurationLoader, ArchyConfigurationLoader>();
services.AddMediator(options =>
{
    options.Namespace = "Archy.Generated";
    options.ServiceLifetime = ServiceLifetime.Singleton;
    options.Assemblies = [typeof(LocateWorkspaceCommand).Assembly];
});

using var serviceProvider = services.BuildServiceProvider();
var mediator = serviceProvider.GetRequiredService<IMediator>();

return await ArchyCli.RunAsync(args, mediator, serviceProvider, CancellationToken.None);
