namespace Archy.Features.Duplicates.EvaluateDuplicateDetection;

/// <summary>Stable v1 corpus spanning true clones, semantic duplicates, negatives, data shapes, generated code, and feedback history.</summary>
public static class DuplicateEvaluationCorpus
{
    public const string Version = "duplicate-evaluation/v1";

    public static IReadOnlyList<DuplicateEvaluationCase> Cases { get; } =
    [
        Case("structural-clone", "true_clone", """
            public static int Sum(int[] values) { var total = 0; foreach (var value in values) total += value; return total; }
            """, """
            public static int AddAll(int[] values) { var total = 0; foreach (var value in values) total += value; return total; }
            """, DuplicateEvaluationExpectation.LikelyDuplicate),
        Case("semantic-duplicate", "semantic_duplicate", """
            public static bool HasAccess(User user) => user.IsAdmin || user.Permissions.Contains("orders.read");
            """, """
            public static bool CanReadOrders(User user) { if (user.IsAdmin) return true; return user.Permissions.Any(permission => permission == "orders.read"); }
            """, DuplicateEvaluationExpectation.LikelyDuplicate),
        Case("unrelated-structural", "false_positive_guard", """
            public static int CountPositive(int[] values) { var count = 0; foreach (var value in values) if (value > 0) count++; return count; }
            """, """
            public static int CountFailures(Result[] values) { var count = 0; foreach (var value in values) if (value.IsFailure) count++; return count; }
            """, DuplicateEvaluationExpectation.NotDuplicate),
        Case("dto-record", "data_shape", """
            public sealed record CreateOrderDto(string CustomerId, decimal Total);
            """, """
            public sealed record OrderSubmission(string CustomerId, decimal Total);
            """, DuplicateEvaluationExpectation.DataShapeNamingAdvisory),
        Case("generated-clone", "generated_source", """
            // <auto-generated />
            public partial class ApiClient { public int Get() => 42; }
            """, """
            // <auto-generated />
            public partial class OtherClient { public int Get() => 42; }
            """, DuplicateEvaluationExpectation.ExcludedGeneratedSource),
        Case("ignored-pair", "historical_ignore", """
            public static string Normalize(string value) => value.Trim().ToUpperInvariant();
            """, """
            public static string Canonicalize(string value) => value.Trim().ToUpperInvariant();
            """, DuplicateEvaluationExpectation.SuppressedByExactDecision),
        Case("accepted-pair", "historical_accept", """
            public static decimal ApplyTax(decimal amount) => Math.Round(amount * 1.2m, 2);
            """, """
            public static decimal AddVat(decimal amount) => Math.Round(amount * 1.2m, 2);
            """, DuplicateEvaluationExpectation.LikelyDuplicate),
    ];

    private static DuplicateEvaluationCase Case(string id, string category, string left, string right, DuplicateEvaluationExpectation expected) => new(id, category, left, right, expected);
}
